//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.DeployerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DeployerService.IDeployer")]
    public interface IDeployer {
        
        // CODEGEN: Generating message contract since the operation SendFile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeployer/SendFile", ReplyAction="http://tempuri.org/IDeployer/SendFileResponse")]
        Client.DeployerService.SendFileResponse SendFile(Client.DeployerService.RemoteFile request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeployer/SendFile", ReplyAction="http://tempuri.org/IDeployer/SendFileResponse")]
        System.Threading.Tasks.Task<Client.DeployerService.SendFileResponse> SendFileAsync(Client.DeployerService.RemoteFile request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeployer/GetAllFiles", ReplyAction="http://tempuri.org/IDeployer/GetAllFilesResponse")]
        Logic.FileDetail[] GetAllFiles(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeployer/GetAllFiles", ReplyAction="http://tempuri.org/IDeployer/GetAllFilesResponse")]
        System.Threading.Tasks.Task<Logic.FileDetail[]> GetAllFilesAsync(string path);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoteFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoteFile {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FullPath;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream Stream;
        
        public RemoteFile() {
        }
        
        public RemoteFile(string FullPath, System.IO.Stream Stream) {
            this.FullPath = FullPath;
            this.Stream = Stream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendFileResponse {
        
        public SendFileResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDeployerChannel : Client.DeployerService.IDeployer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeployerClient : System.ServiceModel.ClientBase<Client.DeployerService.IDeployer>, Client.DeployerService.IDeployer {
        
        public DeployerClient() {
        }
        
        public DeployerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeployerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeployerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeployerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.DeployerService.SendFileResponse Client.DeployerService.IDeployer.SendFile(Client.DeployerService.RemoteFile request) {
            return base.Channel.SendFile(request);
        }
        
        public void SendFile(string FullPath, System.IO.Stream Stream) {
            Client.DeployerService.RemoteFile inValue = new Client.DeployerService.RemoteFile();
            inValue.FullPath = FullPath;
            inValue.Stream = Stream;
            Client.DeployerService.SendFileResponse retVal = ((Client.DeployerService.IDeployer)(this)).SendFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.DeployerService.SendFileResponse> Client.DeployerService.IDeployer.SendFileAsync(Client.DeployerService.RemoteFile request) {
            return base.Channel.SendFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.DeployerService.SendFileResponse> SendFileAsync(string FullPath, System.IO.Stream Stream) {
            Client.DeployerService.RemoteFile inValue = new Client.DeployerService.RemoteFile();
            inValue.FullPath = FullPath;
            inValue.Stream = Stream;
            return ((Client.DeployerService.IDeployer)(this)).SendFileAsync(inValue);
        }
        
        public Logic.FileDetail[] GetAllFiles(string path) {
            return base.Channel.GetAllFiles(path);
        }
        
        public System.Threading.Tasks.Task<Logic.FileDetail[]> GetAllFilesAsync(string path) {
            return base.Channel.GetAllFilesAsync(path);
        }
    }
}
